### ISSUE TITLE
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'

### ISSUE THREAD

**Issue by sshaw** [ianks/octodown#129]
```
/ >gem install octodown
Fetching octodown-1.9.2.gem
Successfully installed octodown-1.9.2
1 gem installed
/ >octodown something.md
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Traceback (most recent call last):
	16: from /Users/sshaw/.asdf/installs/ruby/2.7.6/bin/octodown:23:in `<main>'
	15: from /Users/sshaw/.asdf/installs/ruby/2.7.6/bin/octodown:23:in `load'
	14: from /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/octodown-1.9.2/bin/octodown:4:in `<top (required)>'
	13: from /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	12: from /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	11: from /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/octodown-1.9.2/lib/octodown.rb:8:in `<top (required)>'
	10: from /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 9: from /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 8: from /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/octodown-1.9.2/lib/octodown/renderer/server.rb:3:in `<top (required)>'
	 7: from /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 6: from /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 5: from /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/faye-websocket-0.11.1/lib/faye/websocket.rb:10:in `<top (required)>'
	 4: from /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 3: from /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 2: from /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `<top (required)>'
	 1: from /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': dlopen(/Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle, 0x0009): symbol not found in flat namespace (_BIO_ctrl) - /Users/sshaw/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle (LoadError)
```

Any reason to not use the pure ruby version suggested by the message? The less dependencies the better is always a good rule for command-line programs.

**Comment by sshaw** [comment]
> Any reason to not use the pure ruby version suggested by the message? 

To be clear, you'd call `require 'em/pure_ruby'` in `octodown/renderer/server.rb` _before_  `require 'faye/websocket'`
