### ISSUE TITLE
Ruby's URI Can't Parse URL Fragments With "#"

### ISSUE THREAD

**Issue by sshaw** [ianks/octodown#53]
Any fragment with a `#` cannot be parsed by `URI`:

```
/tmp >octodown README.md
/Users/sshaw/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/common.rb:176:in `split': bad URI(is not URI?): #array#bsearch-vs-array#find-codecodearraybsearch-vs-findrb (URI::InvalidURIError)
	from /Users/sshaw/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
	from /Users/sshaw/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/octodown-1.0.4/lib/octodown/support/relative_root_filter.rb:22:in `http_uri?'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/octodown-1.0.4/lib/octodown/support/relative_root_filter.rb:55:in `block in filter_links'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:237:in `block in each'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:236:in `upto'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:236:in `each'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/octodown-1.0.4/lib/octodown/support/relative_root_filter.rb:48:in `filter_links'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/octodown-1.0.4/lib/octodown/support/relative_root_filter.rb:12:in `call'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/html-pipeline-1.11.0/lib/html/pipeline/filter.rb:137:in `call'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/html-pipeline-1.11.0/lib/html/pipeline.rb:121:in `block in perform_filter'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/html-pipeline-1.11.0/lib/html/pipeline.rb:159:in `instrument'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/html-pipeline-1.11.0/lib/html/pipeline.rb:120:in `perform_filter'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/html-pipeline-1.11.0/lib/html/pipeline.rb:106:in `block (2 levels) in call'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/html-pipeline-1.11.0/lib/html/pipeline.rb:105:in `each'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/html-pipeline-1.11.0/lib/html/pipeline.rb:105:in `inject'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/html-pipeline-1.11.0/lib/html/pipeline.rb:105:in `block in call'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/html-pipeline-1.11.0/lib/html/pipeline.rb:159:in `instrument'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/html-pipeline-1.11.0/lib/html/pipeline.rb:103:in `call'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/octodown-1.0.4/lib/octodown/renderer/github_markdown.rb:17:in `to_html'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/octodown-1.0.4/lib/octodown/support/helpers.rb:14:in `markdown_to_raw_html'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/octodown-1.0.4/lib/octodown/support/helpers.rb:8:in `markdown_to_html'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/octodown-1.0.4/bin/octodown:42:in `main'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/gems/octodown-1.0.4/bin/octodown:47:in `<top (required)>'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/bin/octodown:23:in `load'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/bin/octodown:23:in `<main>'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sshaw/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ianks** [comment]
Can you send the URL you are trying to parse so I can recreate it here?

**Comment by sshaw** [comment]
Sorry, it was in the stacktrace: `#array#bsearch-vs-array#find-codecodearraybsearch-vs-findrb`
